# Generated by Django 4.2.5 on 2024-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
